on: [push]

permissions:
  id-token: write

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log GHA ID JWT Claims
        uses: actions/github-script@v6
        with:
          script: |
            let webIdentityToken = await core.getIDToken();
            let parsed = JSON.parse(
              Buffer.from(webIdentityToken.split(".")[1], "base64").toString("utf-8")
            );
            core.info(JSON.stringify(parsed, null, 2));
